apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  labels:
    name: frontend-app-service
    app: assignment-app
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: frontend-app-pod
    app: assignment-app